name: grav
description: |
  Grav is a Fast, Simple, and Flexible, file-based Web-platform. There is Zero installation required. Just extract the ZIP archive, and you are already up and running. It follows similar principles to other flat-file CMS platforms, but has a different design philosophy than most. Grav comes with a powerful Package Management System to allow for simple installation and upgrading of plugins and themes, as well as simple updating of Grav itself.
version: 1.4.8-rancher1
category: CMS
maintainer: "TLE06 <tle@tlnk.fr>"
license: MIT
projectURL: https://github.com/tle06/rancher-catalog
