version: '2'
volumes:
  $${volume_wiki_config}:
    {{- if ne .Values.volume_driver "local"}}
    external: true
    {{- end}}
    driver: ${volume_driver}
  ${volume_wiki_data}:
    {{- if ne .Values.volume_driver "local"}}
    external: true
    {{- end}}
    driver: ${volume_driver}
  ${volume_mongo}:
    {{- if ne .Values.volume_driver "local"}}
    external: true
    {{- end}}
    driver: ${volume_driver}
  ${volume_wiki_repo}:
    {{- if ne .Values.volume_driver "local"}}
    external: true
    {{- end}}
    driver: ${volume_driver}
services:
  wiki:
    image: requarks/wiki
    environment:
      WIKI_ADMIN_EMAIL: ${wiki_admin_email}
    stdin_open: true
    volumes:
    - ${volume_wiki_data}:/var/wiki/data
    - ${volume_wiki_config}:/var/wiki/config
    - ${volume_wiki_repo}:/var/wiki/repo
    tty: true
    links:
    - wiki-db:db
    ports:
    - ${host_port}:80/tcp
    labels:
    {{- if eq .Values.traefik_integration "true"}}
      traefik.frontend.rule: Host:${traefik_frontend_rule}
      traefik.enable: 'true'
      traefik.backend: ${traefik_backend}
      traefik.port: '80'
    {{- end}}
      io.rancher.container.pull_image: always
  wiki-db:
    image: mongo
    stdin_open: true
    volumes:
    - ${volume_mongo}:/data/db
    tty: true
    ports:
    - ${mongo_port}:27017/tcp
    command:
    - --smallfiles
    - --bind_ip
    - wiki-db
    labels:
      io.rancher.container.pull_image: always