version: '2'
catalog:
  name: Wiki-js
  version: 1.0.78-rancher1
  description: An open source, modern and powerful wiki app built on Node.js, Git and Markdown.
  minimum_rancher_version: 1.6.17
  questions:
    - variable: "volume_driver"
      description: "The volume driver shared to store data"
      label: "Volume Driver"
      required: true
      default: "rancher-nfs"
      type: enum
      options:
        - local
        - rancher-nfs
        - rancher-efs
        - rancher-ebs
    - variable: "wiki_admin_email"
      label: "Choose admin email:"
      description: "This email will be use to build the first user for local authentication with default password admin123"
      default: "admin@local.lan"
      required: true
      type: "string"
      - variable: "connection_string"
      label: "Mongo DB connectino string:"
      description: "Format should follow this mongodb://localhost:27017/wiki"
      default: "mongodb://localhost:27017/wiki"
      required: true
      type: "string"
      - variable: "wiki_host"
      label: "Host name:"
      description: "url like http://localhost"
      default: "http://localhost"
      required: true
      type: "string"
    - variable: "volume_wiki_data"
      label: "Choose where to bind the data volume:"
      description: "to bind <your folder>:/var/wiki/data"
      default: "wiki-data"
      required: true
      type: "string"
    - variable: "volume_wiki_config"
      label: "Choose where to bind the config volume:"
      description: "to bind <your folder>:/var/wiki/config"
      default: "wiki-config"
      required: true
      type: "string"
    - variable: "volume_wiki_repo"
      label: "Choose where to bind the repo volume:"
      description: "to bind <your folder>:/var/wiki/repo"
      default: "wiki-repo"
      required: true
      type: "string"
    - variable: "host_port"
      label: "Which port should be used:"
      description: "service will be bind to <port>:80/tcp"
      default: 52827
      required: true
      type: "int"
    - variable: "volume_mongo"
      label: "Choose where to bind the mongo volume:"
      description: "to bind <your folder>:/data/db"
      default: "wiki-db"
      required: true
      type: "string"
    - variable: "mongo_port"
      label: "Which external port for mongo:"
      description: "service will be bind to <port>:27017/tcp"
      default: 54080
      required: true
      type: "int"
    - variable: "traefik_integration"
      label: "Enable trafic integration:"
      description: "Will add traefik.frontend.rule & traefik_backend & traefik.enable: true & traefik.port: 80"
      default: true
      required: true
      type: enum
      options:
        - true
        - false
    - variable: "traefik_frontend_rule"
      label: "traefik.frontend.rule:"
      description: ""
      default: "wikijs.local.lan"
      required: false
      type: "string"
    - variable: "traefik_backend"
      label: "traefik.backend"
      description: ""
      default: "wiki"
      required: false
      type: "string"
services:
  wiki:
    scale: 1
    start_on_create: true
  wiki-db:
    scale: 1
    start_on_create: true