.catalog:
  name: Wiki.js
  version: 1.0.78-rancher1
  description: An open source, modern and powerful wiki app built on Node.js, Git and Markdown.
  uuid: 1.0.78
  minimum_rancher_version: 1.6.17
  questions: #Used to request user input for configuration options
